### ISSUE TITLE
API: ~/index/login/getcode

### ISSUE THREAD

**Issue by msq0313** [2020NCOV/MiniProgram-server-JAVA#6]
功能实现：
- 参考接口文档：[接口文档](https://github.com/2020NCOV/ncov-report/blob/master/api/wxmp/getcode.md)
- 需要在微信开发文档中了解用户登录验证这部分的内容：[文档入口](https://developers.weixin.qq.com/miniprogram/dev/framework/open-ability/login.html)
- 参考文档：[springboot官方文档](https://spring.io/projects/spring-boot/)、[中文文档](https://www.breakyizhan.com/springboot/3028.html)

**Comment by bxzma** [comment]
1

**Comment by msq0313** [comment]
Good job.
